using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Wedding_Management_System
{
    public class UserAction:ISaveUpdateDTO
    {
        public int Save(PostUserDTO post)
        {
            UserRegistration entityUser = new UserRegistration();

            #region :: DTO Properties they come from browser :: Customer
            entityUser.firstName = post.firstName;
            entityUser.middleName = post.middleName;
            entityUser.lastName = post.lastName;
            entityUser.userName = post.userName;
            entityUser.password = post.password;
            #endregion

            #region :: Auto Generated by Server :: BY CODE by DEveloper
            entityUser.createdBy = 1;
            entityUser.createdOn = DateTime.Now;
            entityUser.modifiedBy = 1;
            entityUser.modifiedOn = DateTime.Now;
            entityUser.isDeleted = false;
            #endregion

            return 1;
        }
        public int Update(PutUserDTO put)
        {
            UserRegistration entityUser = new UserRegistration();

            #region :: DTO Properties they come from browser :: Customer
            entityUser.firstName = put.firstName;
            entityUser.middleName = put.middleName;
            entityUser.lastName = put.lastName;
            entityUser.userName = put.userName;
            entityUser.password = put.password;
            #endregion

            #region :: Auto Generated by Server :: BY CODE by DEveloper
            entityUser.createdBy = 1;
            entityUser.createdOn = DateTime.Now;
            entityUser.modifiedBy = 1;
            entityUser.modifiedOn = DateTime.Now;
            entityUser.isDeleted = false;
            #endregion
            return 1;
        }
    }
}
